### ISSUE TITLE
Bash completion scripts 

### ISSUE THREAD

**Issue by cv** [cv/crab#19]

**Comment by rafb43** [comment]
Ok, it's pretty much worked out, there's one thing left and I'm having a bit of trouble with it. Can you guys please try it out?

Known issues:
- Lists .swp as possible completions as it relies on files on `bin/`
- Doesn't present same behavior `git` completion has on ambiguous completions. Like when you <tab> and then <tab> again so it shows the possibilities and lead you back to the command line. It's currently printing things on top of your line and making a mess. I looked over `/etc/bash_completion.d/git` but couldn't figure out anything

Anything else?

**Comment by cv** [comment]
DUDE!

You totally nailed it! Thanks! :)

I found out that the only difference between what git does and what we were doing is that bash expects COMPREPLY to be an array like FOO=() instead of a string (as we were giving it at the end of the command.

Works like a charm now, I'm considering dropping the "built-in" aliases since now it's easier to just complete :D
