### ISSUE TITLE
"crab testcase list" / "crab testcase list -P"  return all test cases from the project we are logged in, but in some moment it returns a null error

### ISSUE THREAD

**Issue by camiloribeiro** [cv/crab#2]
"crab testcase list" / "crab testcase list -P"  return all test cases from the project we are logged in, but in some moment it returns an error:
   /var/lib/gems/1.8/gems/crab-0.2.8/lib/crab/story.rb:25:in `formatted_id': undefined method`formatted_i_d' for nil:NilClass (NoMethodError)
    from /var/lib/gems/1.8/gems/crab-0.2.8/bin/crab-testcase-list:38:in `run'
    from /var/lib/gems/1.8/gems/crab-0.2.8/bin/crab-testcase-list:37:in`each'
    from /var/lib/gems/1.8/gems/crab-0.2.8/bin/crab-testcase-list:37:in `run'
    from /var/lib/gems/1.8/gems/crab-0.2.8/lib/crab/rally.rb:11:in`initialize'
    from /var/lib/gems/1.8/gems/crab-0.2.8/bin/crab-testcase-list:30:in `new'
    from /var/lib/gems/1.8/gems/crab-0.2.8/bin/crab-testcase-list:30:in`run'
    from /var/lib/gems/1.8/gems/crab-0.2.8/bin/crab-testcase-list:45
    from /usr/local/bin/crab-testcase-list:19:in `load'
    from /usr/local/bin/crab-testcase-list:19

**Comment by cv** [comment]
0.2.9 (later today) will contain the fix :)
