### ISSUE TITLE
"Crab testcase list -P Critical" isn't filtering (as well as -r and -m)

### ISSUE THREAD

**Issue by camiloribeiro** [cv/crab#3]
"Crab testcase list -P Critical" isn't filtering (as well as -r and -m)

Using project X, when I try use some parameter to filter like "crab testcase find -m manual" it is not working.

Return all test cases

It should return just the test cases with method = manual

The same is happening to risk and priority

**Comment by cv** [comment]
Will be in the 0.2.9 release as well. :)
