### ISSUE TITLE
Enhancement: Change status by parameter 

### ISSUE THREAD

**Issue by camiloribeiro** [cv/crab#4]
I know that the command move is to move forward or back, but it was nice if I could pass the State after the US Number, like this:

Trace:
camilo@c-ubuntu:~$ crab story move US5158 Defined
I, [2011-10-03T19:26:09.620888 #10575]  INFO -- crab: Getting credentials...
I, [2011-10-03T19:26:09.621188 #10575]  INFO -- crab: Connecting to Rally as xxxxxx@thoughtworks.com...
I, [2011-10-03T19:26:11.177161 #10575]  INFO -- crab: Looking up story with ID US5158 Defined
US5158: Bla bla bla story (defined)
camilo@c-ubuntu:~$ crab story move US5158 Completed
I, [2011-10-03T19:26:48.963299 #10617]  INFO -- crab: Getting credentials...
I, [2011-10-03T19:26:48.963602 #10617]  INFO -- crab: Connecting to Rally as xxxxxx@thoughtworks.com...
I, [2011-10-03T19:26:49.767937 #10617]  INFO -- crab: Looking up story with ID US5158 Completed
US5158: Bla bla bla story (in_progress)
camilo@c-ubuntu:~$ crab story move US5158 Defined
I, [2011-10-03T19:27:20.031225 #10645]  INFO -- crab: Getting credentials...
I, [2011-10-03T19:27:20.031541 #10645]  INFO -- crab: Connecting to Rally as xxxxxx@thoughtworks.com...
I, [2011-10-03T19:27:20.967143 #10645]  INFO -- crab: Looking up story with ID US5158 Defined
US5158: Bla bla bla story (completed)

**Comment by cv** [comment]
Done! :)

Will be in on the next release.
