### ISSUE TITLE
Recursively look for .crab

### ISSUE THREAD

**Issue by cv** [cv/crab#7]
Look for .crab like Git does with .git

**Comment by rafb43** [comment]
I don't see a good reason for this to have such a high priority. 0.3.0, why?

**Comment by cv** [comment]
Because if we do that, it'll be possible to work in multiple projects and call crab to do things without necessarily having to cd back into the project root.

I'm happy to move it to 0.4 or later, but I'd like that to be in place before we implement .crab/config or start working on encryption.

**Comment by fgrehm** [comment]
Hey guys, check out the [recursively-look-for-dotcrab](https://github.com/cv/crab/compare/recursively-look-for-dotcrab) branch, I've implemented support for selected project and also for project specific credentials.
As I told you I'm not able to run all cucumber tests so make sure you run it before merging it back into master :-)

**Comment by cv** [comment]
Awesome!

I had to make a few changes so the tests would pass -- and ended up adding the 'crab project --clear' command in the process. Merging in as soon as the entire suite goes green.

Thanks, dude! :D
